epochs: 40
output_dir: output_dir

model:
  name: BYOL
  backbone:
    name: ResNet
    depth: 50
    with_pool: True
  neck:
    name: NonLinearNeckV2
    in_channels: 2048
    hid_channels: 4096
    out_channels: 256
    with_avg_pool: False
  predictor:
    name: NonLinearNeckV2
    in_channels: 256
    hid_channels: 4096
    out_channels: 256
    with_avg_pool: False
  head:
    name: L2Head
  target_decay_method: cosine # cosine
  target_decay_rate: 0.97
  align_init_network: True
  use_synch_bn: True

dataloader:
  train:
    num_workers: 4
    sampler:
      batch_size: 128
      shuffle: True
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: False
      return_two_sample: True
      transforms: 
        - name: RandomResizedCrop
          size: 224
          scale: [0.08, 1.]
          interpolation: "bicubic"
        - name: NormToOne
        - name: Clip

      post_view_trans1:
        - name: RandomHorizontalFlip 
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.2
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            sigma: [0.1, 2.0]
          p: 1.0
        - name: RandomApply
          transforms:
          - name: Solarization
            threshold: 0.5
            norm: True
          p: 0.0
        - name: Transpose
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

      post_view_trans2:
        - name: RandomHorizontalFlip 
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.2
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            sigma: [0.1, 2.0]
          p: 0.1
        - name: RandomApply
          transforms:
          - name: Solarization
            threshold: 0.5
            norm: True
          p: 0.2
        - name: Transpose
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

lr_scheduler:
  name: LinearWarmup
  learning_rate:
    name: CosineDecay
    learning_rate: 0.45
    T_max: 38
  warmup_steps: 2
  start_lr: 0.0
  end_lr: 0.45

optimizer:
  name: LarsMomentumOptimizer
  momentum: 0.9
  lars_weight_decay: 1.0e-6
  exclude_from_weight_decay: ['bn', 'batch_norm', '.b_0']

#optimizer:
#  name: Momentum
#  weight_decay: 1e-6

log_config:
    name: LogHook
    interval: 1

custom_config:
  - name: BYOLHook
