epochs: 40
output_dir: output_dir

model:
  name: BYOL
  backbone:
    name: ResNet
    depth: 50
    with_pool: True
  neck:
    name: NonLinearNeckV2
    in_channels: 2048
    hid_channels: 4096
    out_channels: 256
    with_avg_pool: False
  predictor:
    name: NonLinearNeckV2
    in_channels: 256
    hid_channels: 4096
    out_channels: 256
    with_avg_pool: False
  head:
    name: L2Head
  target_decay_method: cosine # cosine
  target_decay_rate: 0.97
  align_init_network: True
  use_synch_bn: True
  num_classes: 1000
  embedding_dim: 2048
  
  

dataloader:
  train:
    num_workers: 4
    sampler:
      batch_size: 128
      shuffle: true
      drop_last: True
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: True
      return_two_sample: True
      transforms:
        - name: RandomResizedCrop
          size: 224
          scale: [0.08, 1.]
          interpolation: "bicubic"
        - name: RandomHorizontalFlip
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        - name: RandomApply
          transforms:
          - name: GaussianBlur
            kernel_size: 23
            sigma: [0.1, 2.0]
            use_cv: True
          p: 0.5
        - name: RandomApply
          transforms:
          - name: Solarization
            threshold: 128
            norm: False
          p: 0.0
        - name: Transpose
        - name: Normalize
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]

lr_scheduler:
  name: LinearWarmup
  learning_rate:
    name: CosineDecay
    learning_rate: 0.225
    T_max: 38
  warmup_steps: 2
  start_lr: 0.0
  end_lr: 0.225

optimizer:
  name: LarsMomentumOptimizer
  momentum: 0.9
  lars_weight_decay: 1.0e-6
  exclude_from_weight_decay: [".b_0","bn","batch_norm",".bias"]
log_config:
    name: LogHook
    interval: 1

custom_config:
  - name: BYOLHook
