epochs: 1000
output_dir: output_dir

model:
  name: SimCLR
  backbone:
    name: ResNet
    depth: 18
    frozen_stages: 4
  neck:
    name: NonLinearNeckfc3
    in_channels: 512
    hid_channels: 512
    out_channels: 128
    with_avg_pool: False
    # with_bn: False
  head:
    name: SimCLRContrastiveHead
    temperature: 0.5

dataloader:
  train:
    num_workers: 0
    sampler:
      # batch_size: 2
      batch_size: 512
      shuffle: true
      drop_last: true
    dataset:
      name: CIFAR10
      # dataroot: data/ILSVRC2012/train
      # dataroot: data/cifar10/train
      # return_label: False
      # return_two_sample: True
      mode: 'train'
      return_label: False
      return_two_sample: True
      download: True
      transforms:
        - name: RandomResizedCrop
          size: 32
          scale: [0.1, 1.]
          interpolation: bicubic
        - name: RandomApply
          transforms:
          - name: ColorJitter
            brightness: 0.4
            contrast: 0.4
            saturation: 0.4
            hue: 0.1
          p: 0.8
        - name: RandomGrayscale
          p: 0.2
        # - name: RandomApply
        #   transforms:
        #   - name: GaussianBlur
        #     sigma: [0.1, 2.0]
        #   p: 0.5
        - name: RandomHorizontalFlip
        - name: Transpose
        - name: Normalize
          # mean: [125.3, 123.0, 113.9]
          # std: [63.0, 62.1, 66.7]
          # mean: [0.4914, 0.4822, 0.4465]
          # std: [0.2023, 0.1994, 0.2010]

  val:
    num_workers: 0
    sampler:
      # batch_size: 64
      batch_size: 512
      shuffle: false
      drop_last: false
    dataset:
      name: Cifar10
      # dataroot: data/ILSVRC2012/val
      # dataroot: data/cifar10/test
      mode: 'test'
      return_label: True
      transforms:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: Transpose
        - name: Normalize
          # mean: [123.675, 116.28, 103.53]
          # std: [58.395, 57.12, 57.375]





lr_scheduler:
  name: CosineWarmup
  learning_rate_scaling: linear
  total_images: 50000
  warmup_epochs: 10
  start_lr: 0
  end_lr: 1.0
  T_max: 200



# lr_scheduler:
#   name: CosineAnnealingDecay
#   learning_rate: 3
#   T_max: 20
# # lr_scheduler:
# #   name: 
  

# learning_rate_scaling:
# lr_scheduler:
#   name: Cosine
#   learning_rate: 1.0
#   T_max: 200


optimizer:
  name: LarsMomentumOptimizer
  momentum: 0.9
  lars_weight_decay: 0.0001
  exclude_from_weight_decay: ['scale', 'offset', 'b_0']
  

# optimizer:
#   name: Momentum
#   momentum: 0.9
#   use_nesterov: True
#   weight_decay: 0.0001

  # momentum: 0.9
  # lars_weight_decay: 0.0001
# optimizer:
#   name: Momentum
#   weight_decay: 0.0001

log_config:
    name: LogHook
    interval: 10


