epochs: 100
output_dir: output_dir

model:
  name: Classification
  backbone:
    name: ResNet
    depth: 50
    with_pool: true
    frozen_stages: 4
  head:
    name: ClasHead
    in_channels: 2048
    num_classes: 1000

dataloader:
  train:
    num_workers: 8
    sampler:
      batch_size: 512
      shuffle: true
      drop_last: False
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/train
      return_label: True
      transforms:
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name : ByolNormalize
        #- name: Transpose
        #- name: Normalize
        #  mean: [123.675, 116.28, 103.53]
        #  std: [58.395, 57.12, 57.375]
  val:
    num_workers: 8
    sampler:
      batch_size: 128
      shuffle: false
      drop_last: false
    dataset:
      name: ImageNet
      dataroot: data/ILSVRC2012/val
      return_label: True
      transforms:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ByolNormalize
        - name: Clip
        #- name: Transpose
        #- name: Normalize
        #  mean: [123.675, 116.28, 103.53]
        #  std: [58.395, 57.12, 57.375]

lr_scheduler:                                                                                                                                                                               
  name: CosinWarmup                                                                                                                                                                         
  total_image: 1281167                                                                                                                                                                      
  total_batch: 1024                                                                                                                                                                         
  total_steps: 100                                                                                                                                                                          
  warmup_steps: 0                                                                                                                                                                          
  start_lr: 0                                                                                                                                                                               
  end_lr: 4.8


optimizer:
  name: Momentum
  weight_decay: 0.0

log_config:
    name: LogHook
    interval: 10

custom_config:
  - name: EvaluateHook
